### ISSUE TITLE
If XX language do this, else do that...

### ISSUE THREAD

**Issue by pmaojo** [WPGlobus/WPGlobus#4]
Is this possible with your plugin? I need to use translations on the header.php of my template and want to make an if like:

<?php 
if ( PAGEINENGLISH ) { ?> 
stuff in english 
<?php } else { ?> 
stuff in other language 
<?php }; ?>

What to put where I wrote PAGEINENGLISH?

If this is not possible yet. How could I add a class to each body tag with the current language?

thankyou

**Comment by pmaojo** [comment]
Ok. This worked:
<?php if (get_bloginfo('language')=='en-US'){?> 
 The english text<?php } else { ?> The spanish text <?php } ?>

**Comment by tivnet** [comment]
@pmaojo I believe, the way you did it is the best at the moment. There are, of course, direct methods of checking using WPGlobus::Contig() - but because we are still in beta, we cannot guarantee that all those methods will stay as-is. So, yes - checking bloginfo is a great solution.
Thanks for sharing!
