### ISSUE TITLE
Certain permalinks setup don't work with the plugin

### ISSUE THREAD

**Issue by zcuric** [WPGlobus/WPGlobus#9]
First of all, great that you have a Github account :+1: 

Second, you have bug with permalinks, it's a weird case but it happend to me. 
So if i have for example my permalinks setup like this:
`/en/%category%/%postname%/`

And I enable WPGlobus and set two languages EN and HR (Croatian), the permalinks setup will fallback on `/%category%/%postname%/` on every link and all posts will 404.

**Comment by tivnet** [comment]
Hi Zdravko,

WPGlobus works the following way:

- for the default (main language), it does not add any language prefix, so the won't be any `/en/`, just `/category/post/`
- for all other languages, it adds `/{xx}/`, so for Hrvatski, it will be `/hr/category/post/`

What happens if you add `/en/` in the permalinks, WPGlobus finds it and removes, because that's the algorithm for default language. If you do not put `/en/` there manually, everything should work OK.

Why are we doing it this way? Because there should be no duplicate URLs (SEO), and if we have both `/category/post/` and `/en/category/post/` pointing to the same place, Google will report duplication.

**Comment by ZdravkoEE** [comment]
I'm migrating site from old Drupal installation and need permalinks to strictly have both `/en/` and `/hr/` so save the SEO from the old site and to make the links work. If there was a checkbox to disable overriding that would be great.

**Comment by tivnet** [comment]
@ZdravkoEE Do you want to put a rewrite rule in your `.htaccess` to 301 all `/en/` to `/` ? That looks like a proper way of doing things.

**Comment by ZdravkoEE** [comment]
@tivnet Yeah, I could do that. Thanks for the suggestion. :)

**Comment by tivnet** [comment]
```
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^en/(.*)$ /$1 [R=301,L]
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```

**Comment by tivnet** [comment]
Better:
```
RewriteRule ^en/?(.*)$ /$1 [R=301,L]
```

**Comment by ZdravkoEE** [comment]
Oh, great! Thanks! I wanted to do it myself but hey! :+1:

**Comment by tivnet** [comment]
You know, move it into a separate block, before the one that WP writes automatically.

**Comment by tivnet** [comment]
```
# BEGIN WPGlobus
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
# Redirect all /en/cat/post to just /cat/post
RewriteRule ^en/?(.*)$ /$1 [R=301,L]
# END WPGlobus


# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
...
```

**Comment by modymok** [comment]
Hay i have the same Problem , i add two lang's "En" and "Ar", i keeps giving me 404 error when a switch between lang's 

Host Info:
Windows Sever, IIS

**Comment by tivnet** [comment]
@modymok WPGlobus works only with "pretty permalinks". If your server supports it
(http://www.iis.net/learn/extensions/url-rewrite-module/enabling-pretty-permalinks-in-wordpress)
then everything should work OK.

Unfortunately, we do not have any experience with IIS, so we cannot give you any specific recommendations.
